//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICounter", CallbackContract=typeof(ICounterCallback))]
public interface ICounter
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICounter/Increment", ReplyAction="http://tempuri.org/ICounter/IncrementResponse")]
    void Increment();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICounter/Decrement", ReplyAction="http://tempuri.org/ICounter/DecrementResponse")]
    void Decrement();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICounter/GetCount", ReplyAction="http://tempuri.org/ICounter/GetCountResponse")]
    int GetCount();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ICounterCallback
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICounter/CountChanged", ReplyAction="http://tempuri.org/ICounter/CountChangedResponse")]
    void CountChanged(int value);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ICounterChannel : ICounter, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class CounterClient : System.ServiceModel.DuplexClientBase<ICounter>, ICounter
{
    
    public CounterClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public CounterClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    
    public CounterClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public CounterClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public CounterClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    public void Increment()
    {
        base.Channel.Increment();
    }
    
    public void Decrement()
    {
        base.Channel.Decrement();
    }
    
    public int GetCount()
    {
        return base.Channel.GetCount();
    }
}
