//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.StreamServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StreamServiceReference.IStreamServiceContract")]
    public interface IStreamServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStreamServiceContract/EchoStream", ReplyAction="http://tempuri.org/IStreamServiceContract/EchoStreamResponse")]
        System.IO.Stream EchoStream(System.IO.Stream stream);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IStreamServiceContractChannel : Client.StreamServiceReference.IStreamServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class StreamServiceContractClient : System.ServiceModel.ClientBase<Client.StreamServiceReference.IStreamServiceContract>, Client.StreamServiceReference.IStreamServiceContract {
        
        public StreamServiceContractClient() {
        }
        
        public StreamServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StreamServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StreamServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StreamServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream EchoStream(System.IO.Stream stream) {
            return base.Channel.EchoStream(stream);
        }
    }
}
